ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_address VARCHAR(255);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS city VARCHAR(100);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(30);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS country VARCHAR(100);

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS delivery_date DATE;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS note TEXT;