"""fix user unique constraints and add telephone unique

Revision ID: 9153df5a5993
Revises: 
Create Date: 2026-08-21 15:10:06.705112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9153df5a5993'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_telephone'), 'users', ['telephone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telephone'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=True)
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=True)
    # ### end Alembic commands ###
